### ISSUE TITLE
About parse the data "GET /path/to/hoge?a=1&b=2&c=1 HTTP/1.1"

### ISSUE THREAD

**Issue by hiroyuki-sato** [mwed/embulk-filter-query_string#1]
Hello

When the Embulk parse the data `GET /path/to/hoge?a=1&b=2&c=1 HTTP/1.1`
I expect that the output data is a:1, b:2, c:3
But the result is `3 HTTP/1.1`

Does this plugin expect query data part only as input data? (ex: a=1&b=2&c=3)

Query string does not allow space. so It is better to parse like the `c:3`
How do you think this behavior?

I used apache-parser-custom_log plugin it parse `GET /path/to/hoge?a=1&b=2&c=1 HTTP/1.1` as one column. and As far as I know, It is difficult to extract query part with the current plugins.

That is why I asked this question. 

Thanks 

```
GET /path/to/hoge?a=1&b=2&c=3 HTTP/1.1
GET /path/to/hoge?a=1 HTTP/1.1
GET /path/to/hoge?b=2 HTTP/1.1
GET /path/to/hoge?c=3 HTTP/1.1
```

``` yaml
in:
  type: file
  path_prefix: input.txt
  parser:
    type: none
filters:
  - type: query_string
    query_string_column_name: 'payload'
    expanded_columns:
      - { name: a, type: string }
      - { name: b, type: string }
      - { name: c, type: string }
exec:
  min_output_tasks: 1

out:
  type: file
  path_prefix: out
  file_ext: csv
  formatter:
    type: csv
```

``` csv
a,b,c
1,2,3 HTTP/1.1
1 HTTP/1.1,,
,2 HTTP/1.1,
,,3 HTTP/1.1
```
